/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#3d4b5f",
              "surface-container-lowest": "#ffffff",
              "surface-dim": "#cbdbf5",
              "on-primary-fixed": "#001c37",
              "tertiary": "#263448",
              "secondary": "#9d4300",
              "on-primary-fixed-variant": "#07497d",
              "inverse-primary": "#a0c9ff",
              "on-primary-container": "#8ebdf9",
              "secondary-fixed": "#ffdbca",
              "on-background": "#0b1c30",
              "surface-container-highest": "#d3e4fe",
              "surface-variant": "#d3e4fe",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#3a485c",
              "on-surface": "#0b1c30",
              "surface-container": "#e5eeff",
              "inverse-on-surface": "#eaf1ff",
              "on-secondary-fixed-variant": "#783200",
              "secondary-fixed-dim": "#ffb690",
              "primary-fixed": "#d2e4ff",
              "surface": "#f8f9ff",
              "surface-container-low": "#eff4ff",
              "on-tertiary": "#ffffff",
              "on-tertiary-fixed": "#0d1c2f",
              "on-secondary": "#ffffff",
              "on-tertiary-container": "#acbbd3",
              "tertiary-fixed": "#d5e3fd",
              "on-secondary-fixed": "#341100",
              "tertiary-fixed-dim": "#b9c7e0",
              "primary-fixed-dim": "#a0c9ff",
              "surface-bright": "#f8f9ff",
              "on-primary": "#ffffff",
              "primary-container": "#0f4c81",
              "primary": "#00355f",
              "on-error-container": "#93000a",
              "on-secondary-container": "#5c2400",
              "on-surface-variant": "#42474f",
              "secondary-container": "#8A4A00",
              "surface-container-high": "#dce9ff",
              "background": "#f8f9ff",
              "outline": "#727780",
              "outline-variant": "#c2c7d1",
              "error": "#ba1a1a",
              "surface-tint": "#2d6197",
              "on-error": "#ffffff",
              "inverse-surface": "#213145"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "sm": "8px",
              "xl": "32px",
              "lg": "24px",
              "gutter": "20px",
              "margin": "24px",
              "xs": "4px",
              "md": "16px",
              "base": "4px"
      },
      "fontFamily": {
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "headline-xl": ["Inter"],
              "headline-md": ["Inter"],
              "body-md": ["Inter"],
              "label-bold": ["Inter"],
              "tabular-nums": ["Inter"]
      },
      "fontSize": {
              "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
              "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "900"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "800"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "label-bold": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
              "tabular-nums": ["14px", {"lineHeight": "20px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
